// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhgzpjcuronlpnjfgznn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoZ3pwamN1cm9ubHBuamZnem5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTg0NjUsImV4cCI6MjA2NjQzNDQ2NX0.ewY4ECdY4OnEIZmcRbbJtj2LUR82H3G0QLpwj3jHjcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);